source/src/PiotrOsinski/Bundle/Entity/Blog/Post.php
<?php

namespace PiotrOsinski\Bundle\Entity\Blog;

use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Table()
 * @ORM\HasLifecycleCallbacks
 * @ORM\Entity(repositoryClass="PiotrOsinski\Bundle\Entity\Blog\PostRepository")
 * @UniqueEntity("slug")
 * @ORM\HasLifecycleCallbacks()
 */
class Post
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @Assert\NotBlank()
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

    /**
     * @Assert\NotBlank()
     * @ORM\Column(name="content", type="text")
     */
    private $content;
    
    /**
     * @Assert\NotBlank()
     * @ORM\Column(name="excerpt", type="text")
     */
    private $excerpt;
    
    /**
     * @ORM\ManyToMany(targetEntity="Category", inversedBy="posts")
     * @ORM\JoinTable(name="post_category")
     **/
    private $categories;
    
    /**
     * @ORM\Column(name="type", type="integer", options={"comment"="
     *                  0-draft, 
     *                  1-published, 
     *                  2-not published(not accesible), 
     *                  3-accesible only by link"})
     */
    private $type;
    public static $typesList = array(0=>'Szkic',1=>'Opublikowany',2=>'Ukryty',3=>'Dostępny przez link');
    
    /**
     * @ORM\Column(name="updated_at", type="datetime")
     */
    private $updatedAt;
    
    /**
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $createdAt;
    
    /**
     * @ORM\Column(name="slug", type="string", length=255, unique=true, nullable=false)
     */
    private $slug;
    
    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function prePersist()
    {
        $string = $this->getTitle();
        $slug = \PiotrOsinski\Bundle\Service\Helper\Slugizer::get($string);
        $this->setSlug($slug);
    }
    
    public static function generateCacheKey($id = null, $slug = null){
        return 'post:'.$id.':'.substr(md5($slug), 0, 10);
    }
    
    public function getCacheKey(){
        return self::generateCacheKey($this->getId(), $this->getSlug());
    }
    
    /**
     * Get id
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Post
     */
    public function setTitle($title)
    {
        $this->title = $title;
    
        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set content
     *
     * @param string $content
     * @return Post
     */
    public function setContent($content)
    {
        $this->content = $content;
    
        return $this;
    }

    /**
     * Get content
     *
     * @return string 
     */
    public function getContent()
    {
        return $this->content;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->categories = new \Doctrine\Common\Collections\ArrayCollection();
        $this->createdAt = new \DateTime;
        $this->updatedAt = new \DateTime;
    }
    
    /**
     * @ORM\PreUpdate
     */
    public function preUpdate(){
        $this->updatedAt = new \DateTime;
    }
    
    
    /**
     * Get categories
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getCategories()
    {
        return $this->categories;
    }
    
    public function getCategoriesString(){
        $str = array();
        foreach($this->getCategories() as $one){
            $str[] = $one->getName();
        }

        return implode(', ', $str);
    }

    /**
     * Set type
     *
     * @param string $type
     * @return Post
     */
    public function setType($type)
    {
        $this->type = $type;
    
        return $this;
    }

    /**
     * Get type
     *
     * @return string 
     */
    public function getType($translate = false)
    {
        if($translate)
            return self::$typesList[$this->type];
        else
            return $this->type;
    }
    
    public static function getTypesList(){
        return self::$typesList;
    }

    /**
     * Add categories
     *
     * @param \PiotrOsinski\Bundle\Entity\Blog\Post $categories
     * @return Post
     */
    public function addCategorie(\PiotrOsinski\Bundle\Entity\Blog\Category $categories)
    {
        $this->categories[] = $categories;
    
        return $this;
    }

    /**
     * Remove categories
     *
     * @param \PiotrOsinski\Bundle\Entity\Blog\Post $categories
     */
    public function removeCategorie(\PiotrOsinski\Bundle\Entity\Blog\Category $categories)
    {
        $this->categories->removeElement($categories);
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     * @return Post
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;
    
        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime 
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return Post
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    
        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    
    /**
     * Set slug
     *
     * @param string $slug
     * @return Post
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;
    
        return $this;
    }

    /**
     * Get slug
     *
     * @return string 
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Set excerpt
     *
     * @param string $excerpt
     * @return Post
     */
    public function setExcerpt($excerpt)
    {
        $this->excerpt = $excerpt;
    
        return $this;
    }

    /**
     * Get excerpt
     *
     * @return string 
     */
    public function getExcerpt()
    {
        return $this->excerpt;
    }
}

source/src/PiotrOsinski/Bundle/Form/Admin/PostType.php
<?php

namespace PiotrOsinski\Bundle\Form\Admin;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

use PiotrOsinski\Bundle\Form\Extended\PostTypeChoiceList;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('excerpt')
            ->add('content', null, array('attr'=>array('class'=>'js-wysiwyg')))
            ->add('type', 'choice', array(
                'choice_list'=> new PostTypeChoiceList()
            ))
            ->add('categories', null, array(
                'expanded' => true,
                'multiple' => true
            ));
        
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'PiotrOsinski\Bundle\Entity\Blog\Post'
        ));
    }

    public function getName()
    {
        return 'piotrosinski_blogbundle_blog_posttype';
    }
}

source/src/PiotrOsinski/Bundle/Controller/Admin/PostController.php
<?php

namespace PiotrOsinski\Bundle\Controller\Admin;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use PiotrOsinski\Bundle\Entity\Blog\Post;
use PiotrOsinski\Bundle\Form\Admin\PostType;

/**
 * Blog\Post controller.
 *
 * @Route("/admin/post")
 */
class PostController extends Controller
{
    /**
     * Lists all Blog\Post entities.
     *
     * @Route("/list/{type}", name="admin_post", defaults={"type"=0})
     * @Method("GET")
     * @Template()
     */
    public function indexAction($type)
    {
        $em = $this->getDoctrine()->getManager();

        $q = $em->getRepository('PiotrOsinskiBundle:Blog\Post')
                ->createQueryBuilder('p')
                ->select('p', 'c')
                ->leftJoin('p.categories', 'c')
                ->where('p.type = :type')
                ->setParameter(':type',$type);
        
        $paginator  = $this->get('knp_paginator');
        $pager = $paginator->paginate(
            $q,
            $this->get('request')->query->get('page', 1)/*page number*/,
            20/*limit per page*/
        );
        
        $postTypes = Post::getTypesList();
        
        $ptc = $em->getRepository('PiotrOsinskiBundle:Blog\Post')
                ->createQueryBuilder('p')
                ->select('count(p), p.type')
                ->groupBy('p.type')
                ->getQuery()
                ->getResult();
        
        $typeCount = array();
        foreach($ptc as $type){
            $typeCount[$type['type']] = $type[1];
        }
        
        return compact('pager', 'postTypes', 'typeCount');
        }

    /**
     * Creates a new Blog\Post entity.
     *
     * @Route("/create-post", name="admin_post_create")
     * @Method("POST")
     * @Template("PiotrOsinskiBundle:Admin\Post:new.html.twig")
     */
    public function createAction(Request $request)
    {
        $entity  = new Post();
        $form = $this->createForm(new PostType(), $entity);
        $form->bind($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('admin_post_show', array('id' => $entity->getId())));
        }

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Displays a form to create a new Blog\Post entity.
     *
     * @Route("/new", name="admin_post_new")
     * @Method("GET")
     * @Template()
     */
    public function newAction()
    {
        $entity = new Post();
        $form   = $this->createForm(new PostType(), $entity);

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Finds and displays a Blog\Post entity.
     *
     * @Route("/{id}", name="admin_post_show")
     * @Method("GET")
     * @Template()
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('PiotrOsinskiBundle:Blog\Post')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Blog\Post entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Displays a form to edit an existing Blog\Post entity.
     *
     * @Route("/{id}/edit", name="admin_post_edit")
     * @Method("GET")
     * @Template("PiotrOsinskiBundle:Admin\Post:new.html.twig")
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('PiotrOsinskiBundle:Blog\Post')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Blog\Post entity.');
        }

        $editForm = $this->createForm(new PostType(), $entity);
        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Edits an existing Blog\Post entity.
     *
     * @Route("/{id}", name="admin_post_update")
     * @Method("PUT")
     * @Template("PiotrOsinskiBundle:Admin\Post:new.html.twig")
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('PiotrOsinskiBundle:Blog\Post')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Blog\Post entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createForm(new PostType(), $entity);
        $editForm->bind($request);

        if ($editForm->isValid()) {
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('admin_post_edit', array('id' => $id)));
        }

        return array(
            'entity'      => $entity,
            'form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Deletes a Blog\Post entity.
     *
     * @Route("/{id}", name="admin_post_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->bind($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('PiotrOsinskiBundle:Blog\Post')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Blog\Post entity.');
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('admin_post'));
    }

    /**
     * Creates a form to delete a Blog\Post entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder(array('id' => $id))
            ->add('id', 'hidden')
            ->getForm()
        ;
    }
}

source/src/PiotrOsinski/Bundle/Resources/views/Admin/Post/index.html.twig
{% extends '::baseAdmin.html.twig' %}

{% block body -%}
    <header>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ path('admin_post_new') }}" class="btn btn-small">Dodaj</a>
            
            <div class="btn-group">
                {% for key, type in postTypes %}
                    {% if typeCount[key] is defined %}
                      {% set count = typeCount[key] %}
                    {% else %}
                      {% set count = 0 %}
                    {% endif %}
                    <a class="btn {% if app.request.get('type') == key%}active{%endif%}" 
                       href="{{path('admin_post',{'type':key})}}">{{type}} ({{count}})</a>
                {% endfor %}
            </div>
        </div>
        <h1>Wpisy</h1>
      </header>

    <table class="records_list table">
        <thead>
            <tr>
                <th>Tytuł</th>
                <th>Kategorie</th>
                <th>Data dodania</th>
                <th>Ostatnia edycja</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for entity in pager %}
            <tr>
                <td>{{ entity.title }}</td>
                <td>{{ entity.categoriesString }}</td>
                <td>{{ entity.createdAt|date('d-m-Y H:i') }}</td>
                <td>{{ entity.updatedAt|date('d-m-Y H:i') }}</td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-small" title="Podgląd" href="{{ path('admin_post_show', { 'id': entity.id }) }}">
                            <i class="icon-eye-close"></i>
                        </a>
                        <a class="btn btn-small" title="Pokaż" href="{{ path('admin_post_show', { 'id': entity.id }) }}">
                            pokaż
                        </a>
                        <a class="btn btn-small btn-primary" title="Edycja" href="{{ path('admin_post_edit', { 'id': entity.id }) }}">
                            <i class="icon-edit icon-white"></i>
                        </a>
                        </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
<div class="navigation">
    {% include 'PiotrOsinskiBundle:Admin:pagination.html.twig' with {'pager':pager}%}
</div>
    {% endblock %}

source/src/PiotrOsinski/Bundle/Resources/views/Admin/Post/new.html.twig
{% extends '::baseAdmin.html.twig' %}

{% block body -%}
<div class="form-container js-no-prettyprint">
    <h1>Blog\Post {% if delete_form is defined %}edit{%else%}creation{%endif%}</h1>

    <form action="{% if delete_form is defined %}{{ path('admin_post_update', { 'id': entity.id }) }}
{% else %}{{ path('admin_post_create') }}{%endif%}" method="post" {{ form_enctype(form) }} novalidate>
            
        {% if delete_form is defined %}
            <input type="hidden" name="_method" value="PUT" />
        {% endif %}

            {% include 'PiotrOsinskiBundle:Admin:form.html.twig' with {'form':form}%}
        <p>
            <button class="btn btn-primary" type="submit">Zapisz</button>
            <a class="btn" href="{{ path('admin_post') }}">
                Powrót
            </a>
        </p>
    </form>

   {% if delete_form is defined %}
        <form action="{{ path('admin_post_delete', { 'id': entity.id }) }}" method="post">
            <input type="hidden" name="_method" value="DELETE" />
            {{ form_widget(delete_form) }}
            <button class="btn btn-danger" type="submit">Usuń</button>
        </form>
    {% endif %}
    </div>
{% endblock %}

source/src/PiotrOsinski/Bundle/Resources/views/Admin/Post/show.html.twig
{% extends '::baseAdmin.html.twig' %}

{% block body -%}
    <h1>Blog\Post</h1>

    <table class="record_properties">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ entity.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ entity.title }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ entity.content|raw }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ entity.type }}</td>
            </tr>
        </tbody>
    </table>

        <ul class="record_actions">
    <li>
        <a href="{{ path('admin_post') }}">
            Back to the list
        </a>
    </li>
    <li>
        <a href="{{ path('admin_post_edit', { 'id': entity.id }) }}">
            Edit
        </a>
    </li>
    <li>
        <form action="{{ path('admin_post_delete', { 'id': entity.id }) }}" method="post">
            <input type="hidden" name="_method" value="DELETE" />
            {{ form_widget(delete_form) }}
            <button type="submit">Delete</button>
        </form>
    </li>
</ul>
{% endblock %}